### PR TITLE
Small Change: Added more keywords available from both C99 and C11

### PR DESCRIPTION
**Pull request by Noah11012**

### CODE REVIEW

**Review by biraj21 — COMMENTED** [review]
Hi. Thanks for contributing. Right now I'm working on changing the rows array to rows linked list & will also make changes to syntax highlighting. So can you just add '|' at the end of all type related keywords like "_Bool"? Also, I would also appreciate if you could add C++ keywords too. Thanks!;)

**Comment by Noah11012** [comment]
Okay, added the | for the types and added the C++ keywords!

**Review by biraj21 — COMMENTED** [review]
Thanks! Just 1 change now. We'll have to separate C & C++ now. Otherwise C++ keywords will also be highlighted in C file.

So copy all C keywords in a new cpp_keywords & add cpp keywords. c_keywords should only have C keywords.

**Comment by Noah11012** [comment]
Okay, I did it!

**Pull request merged**
